// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX4kH8mC_p8twDDhTnlW-5zHHIo5-SArQ',
    appId: '1:614529383996:web:a1d7c852d45f22cd0d0d39',
    messagingSenderId: '614529383996',
    projectId: 'esmm-3f1ec',
    authDomain: 'esmm-3f1ec.firebaseapp.com',
    storageBucket: 'esmm-3f1ec.appspot.com',
    measurementId: 'G-PRW5BN57SE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgQ0sUZKJYoMF1YeSx468uYN49fA0ZWoA',
    appId: '1:614529383996:android:c220fc5dbd01a69b0d0d39',
    messagingSenderId: '614529383996',
    projectId: 'esmm-3f1ec',
    storageBucket: 'esmm-3f1ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA44vFeQ-Q7uvOwCFCvd_teiDe3_bGsroY',
    appId: '1:614529383996:ios:fece020ac255e1ad0d0d39',
    messagingSenderId: '614529383996',
    projectId: 'esmm-3f1ec',
    storageBucket: 'esmm-3f1ec.appspot.com',
    iosBundleId: 'com.example.rcFlGopoolar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA44vFeQ-Q7uvOwCFCvd_teiDe3_bGsroY',
    appId: '1:614529383996:ios:7d1f25424e3340740d0d39',
    messagingSenderId: '614529383996',
    projectId: 'esmm-3f1ec',
    storageBucket: 'esmm-3f1ec.appspot.com',
    iosBundleId: 'com.example.rcFlGopoolar.RunnerTests',
  );
}
